/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Return service liveness. Contract: ``{"status": "ok"}``.
     */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations['register_api_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Me */
    get: operations['read_me_api_auth_me_get'];
    put?: never;
    post?: never;
    /** Delete Account */
    delete: operations['delete_account_api_auth_me_delete'];
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations['update_me_api_auth_me_patch'];
    trace?: never;
  };
  '/api/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Email */
    post: operations['verify_email_api_auth_verify_email_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend Verification */
    post: operations['resend_verification_api_auth_resend_verification_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Forgot Password */
    post: operations['forgot_password_api_auth_forgot_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Password */
    post: operations['reset_password_api_auth_reset_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Password */
    post: operations['change_password_api_auth_change_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Account */
    get: operations['export_account_api_auth_me_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Profile */
    get: operations['read_profile_api_profile_get'];
    /** Update Profile */
    put: operations['update_profile_api_profile_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sessions */
    get: operations['list_sessions_api_sessions_get'];
    put?: never;
    /** Create Session */
    post: operations['create_session_api_sessions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{session_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Session */
    delete: operations['delete_session_api_sessions__session_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Items */
    get: operations['list_items_api_schedule_get'];
    put?: never;
    /** Create Item */
    post: operations['create_item_api_schedule_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedule/{item_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Item */
    put: operations['update_item_api_schedule__item_id__put'];
    post?: never;
    /** Delete Item */
    delete: operations['delete_item_api_schedule__item_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Dashboard */
    get: operations['get_dashboard_api_dashboard_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/suggestions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suggest */
    post: operations['suggest_api_suggestions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/semesters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Semesters */
    get: operations['list_semesters_api_semesters_get'];
    put?: never;
    /** Create Semester */
    post: operations['create_semester_api_semesters_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/semesters/{semester_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Semester */
    put: operations['update_semester_api_semesters__semester_id__put'];
    post?: never;
    /** Delete Semester */
    delete: operations['delete_semester_api_semesters__semester_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/courses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Courses */
    get: operations['list_courses_api_courses_get'];
    put?: never;
    /** Create Course */
    post: operations['create_course_api_courses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/courses/{course_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Course */
    put: operations['update_course_api_courses__course_id__put'];
    post?: never;
    /** Delete Course */
    delete: operations['delete_course_api_courses__course_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/grades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Grades */
    get: operations['list_grades_api_grades_get'];
    put?: never;
    /** Create Grade */
    post: operations['create_grade_api_grades_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/grades/{grade_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Grade */
    put: operations['update_grade_api_grades__grade_id__put'];
    post?: never;
    /** Delete Grade */
    delete: operations['delete_grade_api_grades__grade_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/gpa': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Gpa */
    get: operations['get_gpa_api_gpa_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/gpa/what-if': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** What If */
    post: operations['what_if_api_gpa_what_if_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/prerequisites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Prerequisites */
    get: operations['list_prerequisites_api_prerequisites_get'];
    put?: never;
    /** Create Prerequisite */
    post: operations['create_prerequisite_api_prerequisites_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/prerequisites/{prereq_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Prerequisite */
    delete: operations['delete_prerequisite_api_prerequisites__prereq_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roadmap/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate */
    post: operations['generate_api_roadmap_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roadmap/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply */
    post: operations['apply_api_roadmap_apply_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/analysis/weak-subjects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Weak Subjects */
    get: operations['weak_subjects_api_analysis_weak_subjects_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/analysis/direction': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Direction */
    get: operations['direction_api_analysis_direction_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/analytics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analytics */
    get: operations['get_analytics_api_analytics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/deadlines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Deadlines */
    get: operations['list_deadlines_api_deadlines_get'];
    put?: never;
    /** Create Deadline */
    post: operations['create_deadline_api_deadlines_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/deadlines/{deadline_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Deadline */
    put: operations['update_deadline_api_deadlines__deadline_id__put'];
    post?: never;
    /** Delete Deadline */
    delete: operations['delete_deadline_api_deadlines__deadline_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Notifications */
    get: operations['list_notifications_api_notifications_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Unread Count */
    get: operations['unread_count_api_notifications_unread_count_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications/{notification_id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Read */
    post: operations['mark_read_api_notifications__notification_id__read_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read All */
    post: operations['read_all_api_notifications_read_all_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountExport */
    AccountExport: {
      user: components['schemas']['UserOut'];
      profile: components['schemas']['ProfileOut'];
      /** Sessions */
      sessions: components['schemas']['StudySessionOut'][];
      /** Schedule */
      schedule: components['schemas']['ScheduleItemOut'][];
      /** Semesters */
      semesters: components['schemas']['SemesterOut'][];
      /** Courses */
      courses: components['schemas']['CourseOut'][];
      /** Grades */
      grades: components['schemas']['GradeOut'][];
      /** Prerequisites */
      prerequisites: components['schemas']['PrerequisiteOut'][];
      /** Deadlines */
      deadlines: components['schemas']['DeadlineOut'][];
      /** Notifications */
      notifications: components['schemas']['NotificationOut'][];
    };
    /** AnalyticsOut */
    AnalyticsOut: {
      /** Heatmap */
      heatmap: components['schemas']['HeatmapPointOut'][];
      /** Time By Method */
      time_by_method: components['schemas']['MethodTimeOut'][];
      /** Time By Course */
      time_by_course: components['schemas']['CourseTimeOut'][];
      /** Focus Trend */
      focus_trend: components['schemas']['FocusPointOut'][];
      weekly_comparison: components['schemas']['WeeklyComparisonOut'];
      monthly_comparison: components['schemas']['MonthlyComparisonOut'];
      productivity_score: components['schemas']['ProductivityScoreOut'];
      /** Hourly Distribution */
      hourly_distribution: components['schemas']['HourlyPointOut'][];
      /** Method Effectiveness */
      method_effectiveness: components['schemas']['MethodEffectivenessOut'][];
    };
    /** BadgeOut */
    BadgeOut: {
      /** Key */
      key: string;
      /** Unlocked */
      unlocked: boolean;
    };
    /** Body_login_api_auth_login_post */
    Body_login_api_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** CategoryStrengthOut */
    CategoryStrengthOut: {
      /** Category */
      category: string;
      /** Avg Grade 4 */
      avg_grade_4: number;
      /** Count */
      count: number;
    };
    /** ChangePasswordIn */
    ChangePasswordIn: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** ChartPointOut */
    ChartPointOut: {
      /** Date */
      date: string;
      /** Minutes */
      minutes: number;
    };
    /** CourseCreate */
    CourseCreate: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Credits */
      credits: number;
      /** Category */
      category?: ('general' | 'foundation' | 'specialized' | 'elective') | null;
      /**
       * Is Required
       * @default true
       */
      is_required: boolean;
      /** Planned Semester Id */
      planned_semester_id?: number | null;
    };
    /** CourseOut */
    CourseOut: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Credits */
      credits: number;
      /** Category */
      category?: ('general' | 'foundation' | 'specialized' | 'elective') | null;
      /**
       * Is Required
       * @default true
       */
      is_required: boolean;
      /** Planned Semester Id */
      planned_semester_id?: number | null;
      /** Id */
      id: number;
    };
    /** CourseSummary */
    CourseSummary: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Credits */
      credits: number;
      /** Category */
      category: string | null;
    };
    /** CourseTimeOut */
    CourseTimeOut: {
      /** Course Id */
      course_id: number | null;
      /** Subject */
      subject: string;
      /** Total Minutes */
      total_minutes: number;
      /** Session Count */
      session_count: number;
    };
    /** CourseUpdate */
    CourseUpdate: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Credits */
      credits: number;
      /** Category */
      category?: ('general' | 'foundation' | 'specialized' | 'elective') | null;
      /**
       * Is Required
       * @default true
       */
      is_required: boolean;
      /** Planned Semester Id */
      planned_semester_id?: number | null;
    };
    /** CreditProgress */
    CreditProgress: {
      /** Earned */
      earned: number;
      /** In Progress */
      in_progress: number;
      /** Remaining */
      remaining: number;
      /** Required */
      required: number;
    };
    /** DashboardOut */
    DashboardOut: {
      kpis: components['schemas']['KpiOut'];
      /** Chart */
      chart: components['schemas']['ChartPointOut'][];
      /** Badges */
      badges: components['schemas']['BadgeOut'][];
      /** Recent Sessions */
      recent_sessions: components['schemas']['StudySessionOut'][];
    };
    /** DeadlineCourseOut */
    DeadlineCourseOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
    };
    /** DeadlineCreate */
    DeadlineCreate: {
      /** Title */
      title: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'assignment' | 'exam' | 'project';
      /**
       * Due At
       * Format: date-time
       */
      due_at: string;
      /** Course Id */
      course_id?: number | null;
      /**
       * Priority
       * @default medium
       * @enum {string}
       */
      priority: 'low' | 'medium' | 'high';
      /** Remind Before Minutes */
      remind_before_minutes?: number | null;
    };
    /** DeadlineOut */
    DeadlineOut: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
      /**
       * Due At
       * Format: date-time
       */
      due_at: string;
      /** Done */
      done: boolean;
      /** Priority */
      priority: string;
      /** Remind Before Minutes */
      remind_before_minutes: number | null;
      /** Reminded At */
      reminded_at: string | null;
      /** Course Id */
      course_id: number | null;
      course?: components['schemas']['DeadlineCourseOut'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** DeadlineUpdate */
    DeadlineUpdate: {
      /** Title */
      title?: string | null;
      /** Type */
      type?: ('assignment' | 'exam' | 'project') | null;
      /** Due At */
      due_at?: string | null;
      /** Course Id */
      course_id?: number | null;
      /** Priority */
      priority?: ('low' | 'medium' | 'high') | null;
      /** Remind Before Minutes */
      remind_before_minutes?: number | null;
      /** Done */
      done?: boolean | null;
    };
    /** DeleteAccountIn */
    DeleteAccountIn: {
      /** Password */
      password: string;
    };
    /** DirectionOut */
    DirectionOut: {
      /** Category Strengths */
      category_strengths: components['schemas']['CategoryStrengthOut'][];
      /** Strongest Category */
      strongest_category: string | null;
      /** Overloaded Semesters */
      overloaded_semesters: components['schemas']['OverloadedSemesterOut'][];
      /** Missing Prerequisites */
      missing_prerequisites: components['schemas']['MissingPrereqOut'][];
    };
    /** FocusPointOut */
    FocusPointOut: {
      /** Date */
      date: string;
      /** Avg Focus */
      avg_focus: number;
    };
    /** ForgotPasswordIn */
    ForgotPasswordIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** GoalSeekOut */
    GoalSeekOut: {
      /** Required Avg */
      required_avg: number | null;
      /** Feasible */
      feasible: boolean;
      /** Already Met */
      already_met: boolean;
      /** Max Reachable Cpa */
      max_reachable_cpa: number;
      /** Remaining Credits */
      remaining_credits: number;
      /** Target Tier */
      target_tier: string;
    };
    /** GpaSummaryOut */
    GpaSummaryOut: {
      /** Cpa */
      cpa: number;
      /** Classification */
      classification: string;
      credits: components['schemas']['CreditProgress'];
      /** Semesters */
      semesters: components['schemas']['SemesterGpa'][];
    };
    /** GradeCreate */
    GradeCreate: {
      /** Course Id */
      course_id: number;
      /** Semester Id */
      semester_id: number;
      /** Grade 10 */
      grade_10?: number | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'in_progress' | 'passed' | 'failed' | 'exempt';
    };
    /** GradeOut */
    GradeOut: {
      /** Id */
      id: number;
      /** Course Id */
      course_id: number;
      /** Semester Id */
      semester_id: number;
      /** Grade 10 */
      grade_10: number | null;
      /** Status */
      status: string;
      /** Letter */
      letter: string | null;
      /** Grade 4 */
      grade_4: number | null;
      course: components['schemas']['CourseSummary'];
      semester: components['schemas']['SemesterSummary'];
    };
    /** GradeUpdate */
    GradeUpdate: {
      /** Course Id */
      course_id: number;
      /** Semester Id */
      semester_id: number;
      /** Grade 10 */
      grade_10?: number | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'in_progress' | 'passed' | 'failed' | 'exempt';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HeatmapPointOut */
    HeatmapPointOut: {
      /** Date */
      date: string;
      /** Minutes */
      minutes: number;
    };
    /** HourlyPointOut */
    HourlyPointOut: {
      /** Hour */
      hour: number;
      /** Total Minutes */
      total_minutes: number;
    };
    /** Hypothetical */
    Hypothetical: {
      /** Credits */
      credits: number;
      /** Grade 10 */
      grade_10: number;
    };
    /** KpiOut */
    KpiOut: {
      /** Today Minutes */
      today_minutes: number;
      /** Total Minutes */
      total_minutes: number;
      /** Total Sessions */
      total_sessions: number;
      /** Streak */
      streak: number;
    };
    /** MeOut */
    MeOut: {
      user: components['schemas']['UserOut'];
      profile: components['schemas']['ProfileOut'];
    };
    /** MethodEffectivenessOut */
    MethodEffectivenessOut: {
      /** Method */
      method: string;
      /** Avg Focus */
      avg_focus: number;
      /** Avg Completion Rate */
      avg_completion_rate: number;
    };
    /** MethodTimeOut */
    MethodTimeOut: {
      /** Method */
      method: string;
      /** Total Minutes */
      total_minutes: number;
      /** Session Count */
      session_count: number;
    };
    /** MissingPrereqOut */
    MissingPrereqOut: {
      /** Course Id */
      course_id: number;
      /** Code */
      code: string | null;
      /** Missing */
      missing: number[];
    };
    /** MonthlyComparisonOut */
    MonthlyComparisonOut: {
      /** This Month Minutes */
      this_month_minutes: number;
      /** Last Month Minutes */
      last_month_minutes: number;
      /** Change Pct */
      change_pct: number | null;
    };
    /** NotificationOut */
    NotificationOut: {
      /** Id */
      id: number;
      /** Type */
      type: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Read */
      read: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** OverloadedSemesterOut */
    OverloadedSemesterOut: {
      /** Code */
      code: string;
      /** Total Credits */
      total_credits: number;
    };
    /** PrerequisiteCreate */
    PrerequisiteCreate: {
      /** Course Id */
      course_id: number;
      /** Prereq Course Id */
      prereq_course_id: number;
    };
    /** PrerequisiteOut */
    PrerequisiteOut: {
      /** Id */
      id: number;
      /** Course Id */
      course_id: number;
      /** Prereq Course Id */
      prereq_course_id: number;
      /** Course Code */
      course_code: string;
      /** Prereq Code */
      prereq_code: string;
    };
    /** ProductivityComponentsOut */
    ProductivityComponentsOut: {
      /** Consistency */
      consistency: number;
      /** Volume */
      volume: number;
      /** Focus Quality */
      focus_quality: number;
    };
    /** ProductivityScoreOut */
    ProductivityScoreOut: {
      /** Score */
      score: number;
      components: components['schemas']['ProductivityComponentsOut'];
    };
    /** ProfileOut */
    ProfileOut: {
      /** Class Name */
      class_name: string;
      /** Faculty */
      faculty: string;
      /** Major */
      major: string;
      /** Goal */
      goal: string;
      /** Avatar Url */
      avatar_url: string | null;
      /** Target Cpa */
      target_cpa: number | null;
      /** Total Credits Required */
      total_credits_required: number | null;
      /** Expected Graduation */
      expected_graduation: string | null;
      /** Max Credits Per Semester */
      max_credits_per_semester: number | null;
    };
    /** ProfileUpdate */
    ProfileUpdate: {
      /** Class Name */
      class_name?: string | null;
      /** Faculty */
      faculty?: string | null;
      /** Major */
      major?: string | null;
      /** Goal */
      goal?: string | null;
      /** Avatar Url */
      avatar_url?: string | null;
      /** Target Cpa */
      target_cpa?: number | null;
      /** Total Credits Required */
      total_credits_required?: number | null;
      /** Expected Graduation */
      expected_graduation?: string | null;
      /** Max Credits Per Semester */
      max_credits_per_semester?: number | null;
    };
    /** ProjectionOut */
    ProjectionOut: {
      /** Projected Cpa */
      projected_cpa: number;
      /** Projected Tier */
      projected_tier: string;
    };
    /** ResetPasswordIn */
    ResetPasswordIn: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /** RoadmapCourseOut */
    RoadmapCourseOut: {
      /** Course Id */
      course_id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Credits */
      credits: number;
      /** Is Required */
      is_required: boolean;
    };
    /** RoadmapIn */
    RoadmapIn: {
      /** Start Code */
      start_code?: string | null;
      /** Max Credits Per Semester */
      max_credits_per_semester?: number | null;
    };
    /** RoadmapOut */
    RoadmapOut: {
      /** Semesters */
      semesters: components['schemas']['RoadmapSemesterOut'][];
      /** Warnings */
      warnings: components['schemas']['RoadmapWarningOut'][];
    };
    /** RoadmapSemesterOut */
    RoadmapSemesterOut: {
      /** Code */
      code: string;
      /** Courses */
      courses: components['schemas']['RoadmapCourseOut'][];
      /** Total Credits */
      total_credits: number;
    };
    /** RoadmapWarningOut */
    RoadmapWarningOut: {
      /** Type */
      type: string;
      /** Course Ids */
      course_ids?: number[] | null;
      /** Detail */
      detail?: string | null;
    };
    /** ScheduleItemCreate */
    ScheduleItemCreate: {
      /** Day Of Week */
      day_of_week: number;
      /** Time */
      time: string;
      /** Subject */
      subject: string;
      /** Course Id */
      course_id?: number | null;
      /**
       * Recurring
       * @default true
       */
      recurring: boolean;
    };
    /** ScheduleItemOut */
    ScheduleItemOut: {
      /** Id */
      id: number;
      /** Day Of Week */
      day_of_week: number;
      /** Time */
      time: string;
      /** Subject */
      subject: string;
      /** Course Id */
      course_id: number | null;
      /** Recurring */
      recurring: boolean;
    };
    /** ScheduleItemUpdate */
    ScheduleItemUpdate: {
      /** Day Of Week */
      day_of_week?: number | null;
      /** Time */
      time?: string | null;
      /** Subject */
      subject?: string | null;
      /** Course Id */
      course_id?: number | null;
      /** Recurring */
      recurring?: boolean | null;
    };
    /** SemesterCreate */
    SemesterCreate: {
      /** Code */
      code: string;
      /** Name */
      name?: string | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SemesterGpa */
    SemesterGpa: {
      /** Semester Id */
      semester_id: number;
      /** Code */
      code: string;
      /** Gpa */
      gpa: number;
      /** Credits */
      credits: number;
    };
    /** SemesterOut */
    SemesterOut: {
      /** Code */
      code: string;
      /** Name */
      name?: string | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Id */
      id: number;
    };
    /** SemesterSummary */
    SemesterSummary: {
      /** Id */
      id: number;
      /** Code */
      code: string;
    };
    /** SemesterUpdate */
    SemesterUpdate: {
      /** Code */
      code: string;
      /** Name */
      name?: string | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SessionCourseOut */
    SessionCourseOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
    };
    /** StudySessionCreate */
    StudySessionCreate: {
      /** Subject */
      subject: string;
      /** Planned Minutes */
      planned_minutes: number;
      /** Actual Minutes */
      actual_minutes: number;
      /** Focus */
      focus: number;
      /**
       * Method
       * @enum {string}
       */
      method: 'Pomodoro' | 'Deep Work' | 'Active Recall';
      /**
       * Note
       * @default
       */
      note: string;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Started At */
      started_at?: string | null;
      /** Ended At */
      ended_at?: string | null;
      /** Course Id */
      course_id?: number | null;
    };
    /** StudySessionOut */
    StudySessionOut: {
      /** Id */
      id: number;
      /** Subject */
      subject: string;
      /** Planned Minutes */
      planned_minutes: number;
      /** Actual Minutes */
      actual_minutes: number;
      /** Focus */
      focus: number;
      /** Method */
      method: string;
      /** Note */
      note: string;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Started At */
      started_at: string | null;
      /** Ended At */
      ended_at: string | null;
      /** Course Id */
      course_id: number | null;
      course?: components['schemas']['SessionCourseOut'] | null;
    };
    /** SuggestionIn */
    SuggestionIn: {
      /**
       * Method
       * @enum {string}
       */
      method: 'Pomodoro' | 'Deep Work' | 'Active Recall';
      /** Focus */
      focus: number;
      /** Planned Minutes */
      planned_minutes: number;
    };
    /** SuggestionOut */
    SuggestionOut: {
      /**
       * Type
       * @enum {string}
       */
      type: 'pomodoro_not_25' | 'high_focus' | 'boost_focus';
      /** Method */
      method: string;
      /** Focus */
      focus: number;
      /** Planned Minutes */
      planned_minutes: number;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UnreadCountOut */
    UnreadCountOut: {
      /** Count */
      count: number;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Name */
      name: string;
      /** Lang */
      lang: string;
      /** Theme */
      theme: string;
      /** Email Verified */
      email_verified: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** UserRegister */
    UserRegister: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Name */
      name: string;
    };
    /** UserSettingsUpdate */
    UserSettingsUpdate: {
      /** Name */
      name?: string | null;
      /** Lang */
      lang?: string | null;
      /** Theme */
      theme?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VerifyEmailIn */
    VerifyEmailIn: {
      /** Token */
      token: string;
    };
    /** WeakSubjectOut */
    WeakSubjectOut: {
      /** Course Id */
      course_id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Signals */
      signals: string[];
      /** Priority */
      priority: string;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
    };
    /** WeeklyComparisonOut */
    WeeklyComparisonOut: {
      /** This Week Minutes */
      this_week_minutes: number;
      /** Last Week Minutes */
      last_week_minutes: number;
      /** Change Pct */
      change_pct: number | null;
    };
    /** WhatIfIn */
    WhatIfIn: {
      /** Target Cpa */
      target_cpa?: number | null;
      /** Total Credits Required */
      total_credits_required?: number | null;
      /** Hypotheticals */
      hypotheticals?: components['schemas']['Hypothetical'][];
    };
    /** WhatIfOut */
    WhatIfOut: {
      goal_seek: components['schemas']['GoalSeekOut'] | null;
      projection: components['schemas']['ProjectionOut'] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  register_api_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserRegister'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_login_api_auth_login_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeOut'];
        };
      };
    };
  };
  delete_account_api_auth_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAccountIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_me_api_auth_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserSettingsUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_email_api_auth_verify_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  resend_verification_api_auth_resend_verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  forgot_password_api_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_password_api_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_password_api_auth_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_account_api_auth_me_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountExport'];
        };
      };
    };
  };
  read_profile_api_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
    };
  };
  update_profile_api_profile_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_sessions_api_sessions_get: {
    parameters: {
      query?: {
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudySessionOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_session_api_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StudySessionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudySessionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_session_api_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_items_api_schedule_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleItemOut'][];
        };
      };
    };
  };
  create_item_api_schedule_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleItemCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleItemOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_item_api_schedule__item_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleItemUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleItemOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_item_api_schedule__item_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_dashboard_api_dashboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardOut'];
        };
      };
    };
  };
  suggest_api_suggestions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SuggestionIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuggestionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_semesters_api_semesters_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SemesterOut'][];
        };
      };
    };
  };
  create_semester_api_semesters_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SemesterCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SemesterOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_semester_api_semesters__semester_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        semester_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SemesterUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SemesterOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_semester_api_semesters__semester_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        semester_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_courses_api_courses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseOut'][];
        };
      };
    };
  };
  create_course_api_courses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CourseCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_course_api_courses__course_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CourseUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_course_api_courses__course_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_grades_api_grades_get: {
    parameters: {
      query?: {
        semester_id?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GradeOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_grade_api_grades_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GradeCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GradeOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_grade_api_grades__grade_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        grade_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GradeUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GradeOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_grade_api_grades__grade_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        grade_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_gpa_api_gpa_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GpaSummaryOut'];
        };
      };
    };
  };
  what_if_api_gpa_what_if_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WhatIfIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WhatIfOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_prerequisites_api_prerequisites_get: {
    parameters: {
      query?: {
        course_id?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrerequisiteOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_prerequisite_api_prerequisites_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PrerequisiteCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrerequisiteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_prerequisite_api_prerequisites__prereq_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prereq_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_api_roadmap_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoadmapIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoadmapOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  apply_api_roadmap_apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoadmapIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoadmapOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  weak_subjects_api_analysis_weak_subjects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeakSubjectOut'][];
        };
      };
    };
  };
  direction_api_analysis_direction_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectionOut'];
        };
      };
    };
  };
  get_analytics_api_analytics_get: {
    parameters: {
      query?: {
        from_date?: string | null;
        to_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnalyticsOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_deadlines_api_deadlines_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeadlineOut'][];
        };
      };
    };
  };
  create_deadline_api_deadlines_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeadlineCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeadlineOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_deadline_api_deadlines__deadline_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deadline_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeadlineUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeadlineOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_deadline_api_deadlines__deadline_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deadline_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_notifications_api_notifications_get: {
    parameters: {
      query?: {
        unread_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  unread_count_api_notifications_unread_count_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnreadCountOut'];
        };
      };
    };
  };
  mark_read_api_notifications__notification_id__read_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notification_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_all_api_notifications_read_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
